In [10]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [11]:
df = pd.read_csv('./Data/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [24]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [4]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [50]:
for i in df.columns:
    print(df[[i]].value_counts())

customerID
0002-ORFBO    1
6616-AALSR    1
6625-UTXEW    1
6625-IUTTT    1
6625-FLENO    1
             ..
3352-RICWQ    1
3352-ALMCK    1
3351-NQLDI    1
3351-NGXYI    1
9995-HOTOH    1
Length: 7043, dtype: int64
gender
1         3555
0         3488
dtype: int64
SeniorCitizen
0                5901
1                1142
dtype: int64
Partner
0          3641
1          3402
dtype: int64
Dependents
0             4933
1             2110
dtype: int64
tenure
1         613
72        362
2         238
3         200
4         176
         ...
28         57
39         56
44         51
36         50
0          11
Length: 73, dtype: int64
PhoneService
1               6361
0                682
dtype: int64
MultipleLines
No                  3390
Yes                 2971
No phone service     682
dtype: int64
InternetService
Fiber optic        3096
DSL                2421
No                 1526
dtype: int64
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
dtype: int64
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
dtype: int64
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
dtype: int64
TechSupport
No                     3473
Yes                    2044
No internet service    1526
dtype: int64
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
dtype: int64
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
dtype: int64
Contract
Month-to-month    3875
Two year          1695
One year          1473
dtype: int64
PaperlessBilling
1                   4171
0                   2872
dtype: int64
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
dtype: int64
MonthlyCharges
20.05             61
19.85             45
19.95             44
19.90             44
19.70             43
                  ..
67.60              1
67.65              1
67.70              1
67.75              1
118.75             1
Length: 1585, dtype: int64
TotalCharges
20.20           11
19.75            9
19.90            8
20.05            8
19.65            8
                ..
927.15           1
927.10           1
926.20           1
926.00           1
8684.80          1
Length: 6530, dtype: int64
Churn
0        5174
1        1869
dtype: int64

In [32]:

for i in df.columns:
    print(df[[i]].nunique())

customerID    7043
dtype: int64
gender    2
dtype: int64
SeniorCitizen    2
dtype: int64
Partner    2
dtype: int64
Dependents    2
dtype: int64
tenure    73
dtype: int64
PhoneService    2
dtype: int64
MultipleLines    3
dtype: int64
InternetService    3
dtype: int64
OnlineSecurity    3
dtype: int64
OnlineBackup    3
dtype: int64
DeviceProtection    3
dtype: int64
TechSupport    3
dtype: int64
StreamingTV    3
dtype: int64
StreamingMovies    3
dtype: int64
Contract    3
dtype: int64
PaperlessBilling    2
dtype: int64
PaymentMethod    4
dtype: int64
MonthlyCharges    1585
dtype: int64
TotalCharges    6531
dtype: int64
Churn    2
dtype: int64

In [ ]:
# Cách 1:
for attribute in ['']
    df[attribute] = df['y'].apply(lambda x: 1 if x=='yes' else 0)

In [ ]:
# Cách 2:
lst = 
sample[lst].map(dict(yes=1, no=0))

## Phân nhóm:
- demography
- services used
- payment amount and method
- churn

## Quick check

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [42]:
# total charge: numeric instead of object
# df['TotalCharges'] = df['TotalCharges'].astype('float64')
df['TotalCharges'] = pd.to_numeric(df.TotalCharges, errors='coerce')
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

## Exploratory Data Analysis

In [43]:
df['Churn'].value_counts()

No     5174
Yes    1869
Name: Churn, dtype: int64

In [ ]:
# pass

## Feature Engineering
Use LabelEncoder and OneHot

In [69]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler

In [63]:
df_transformed = df.copy()

le = LabelEncoder()  # hoac dung apply deu duoc
for i in ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']:
    df_transformed[i] = le.fit_transform(df_transformed[i])

In [65]:
df_transformed.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,1,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,0
2,3668-QPYBK,1,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,1,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

In [67]:
# onehot = OneHotEncoder()
# for i in ['MultipleLines', 'InternetService', 'OnlineSecurity',	'OnlineBackup	DeviceProtection	TechSupport	StreamingTV	StreamingMovies']:
#     df[i] = onehot.fit_transform(df[i])

In [68]:
onehot_list = ['MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaymentMethod']

df_transformed = pd.get_dummies(df_transformed, columns=onehot_list, drop_first=True)
# drop_first = True de bo 1 bien (n-1 bien thay vi n = nunique())

df_transformed.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,0,1,0,1,0,1,29.85,29.85,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
1,5575-GNVDE,1,0,0,0,34,1,0,56.95,1889.50,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
2,3668-QPYBK,1,0,0,0,2,1,1,53.85,108.15,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
3,7795-CFOCW,1,0,0,0,45,0,0,42.30,1840.75,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0
4,9237-HQITU,0,0,0,0,2,1,1,70.70,151.65,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [70]:
### Normalization
### Use the min-max method to rescale the numeric columns (tenure, MonthlyCharges, and TotalCharges) to a common scale
# min-max normalization (numeric variables)

mms = MinMaxScaler()

In [75]:
min_max_col = ['tenure', 'MonthlyCharges', 'TotalCharges']
for col in min_max_col: 
    df_transformed[col] = MinMaxScaler().fit_transform(df[[col]])
df_transformed

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,0,1,0,0.013889,0,1,0.115423,0.001275,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0
1,5575-GNVDE,1,0,0,0,0.472222,1,0,0.385075,0.215867,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1
2,3668-QPYBK,1,0,0,0,0.027778,1,1,0.354229,0.010310,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
3,7795-CFOCW,1,0,0,0,0.625000,0,0,0.239303,0.210241,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0
4,9237-HQITU,0,0,0,0,0.027778,1,1,0.521891,0.015330,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,1,0,1,1,0.333333,1,1,0.662189,0.227521,0,0,1,0,0,0,1,0,0,0,1,0,1,0,1,0,1,1,0,0,0,1
7039,2234-XADUH,0,0,1,1,1.000000,1,1,0.845274,0.847461,0,0,1,1,0,0,0,0,1,0,1,0,0,0,1,0,1,1,0,1,0,0
7040,4801-JZAZL,0,0,1,1,0.152778,0,1,0.112935,0.037809,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7041,8361-LTMKD,1,1,1,0,0.055556,1,1,0.558706,0.033210,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
7042,3186-AJIEK,1,0,0,0,0.916667,1,1,0.869652,0.787641,0,0,0,1,0,0,1,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0